### ISSUE TITLE
WebXR NL community house style checklist

### ISSUE THREAD

**Issue by mkungla** [webxrnl/webxrnl-roadmap#7]
**Description**  

Create all assets and house style design materials

**Subtasks**

> Subject above can be resolved by completing following tasks

- [ ] Logo specifications and examples of usage
- [ ] Typography palette
- [ ] Color palette
- [ ] PowerPoint or Google Slides template
 
- [ ] Overview of WebXR NL brand, including history, vision, slogan and personality
- [ ] Image use specifications, including photography style
- [ ] Design layouts, letterhead, brochures and grids for print and web-based materials
- [ ] Writing style and voice
- [ ] Social media guidelines
- [ ] Visual examples to support each rule (provide examples of proper and improper use for clarity)

**Comment by Dalstam** [comment]
@sorskoot contact with brother

**Comment by michielhamers** [comment]
Also creating PowerPoint templates can become handy. I can assist on that.

**Comment by mkungla** [comment]
We should write some style guidelines based on what we already have

**Comment by Dalstam** [comment]
@sorskoot  what is the status with your brother? Otherwise we need to find a different proposal or person?
